table dim_status
	excludeFromModelRefresh
	lineageTag: c0cbfb2c-d5a8-4414-91fd-0048665d3a5f

	column status
		dataType: string
		lineageTag: cc505ec5-398a-408f-b562-5ea10d6e8066
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column status_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 682a0cb5-d47e-4ef6-a5fc-602a8c9600ac
		summarizeBy: none
		sourceColumn: status_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column status_binary = IF(dim_status[status] = "Default", 1,0)
		formatString: 0
		lineageTag: 8b7f3f20-3d6f-486d-85c0-eb79b578c550
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_status = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "credit_risk_data", [ReturnSingleDatabase=true]),
				    credit_risk_data_credit_risk_dataset = Source{[Schema="credit_risk_data",Item="credit_risk_dataset"]}[Data],
				    #"Added Index" = Table.AddIndexColumn(credit_risk_data_credit_risk_dataset, "Index", 0, 1, Int64.Type),
				    #"Renamed Columns [index]" = Table.RenameColumns(#"Added Index",{{"Index", "record_id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns [index]",{"record_id", "person_age", "person_income", "person_home_ownership", "person_emp_length", "loan_intent", "loan_grade", "loan_amnt", "loan_int_rate", "loan_status", "loan_percent_income", "cb_person_default_on_file", "cb_person_cred_hist_length"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"loan_intent", "purpose"}, {"loan_amnt", "amount"}, {"loan_int_rate", "interest_rate"}, {"loan_percent_income", "loan_to_income"}, {"cb_person_default_on_file", "historic_defaults"}, {"cb_person_cred_hist_length", "credit_history_length"}, {"loan_grade", "grade"}, {"person_emp_length", "employment_length"}, {"person_home_ownership", "residential_status"}, {"person_income", "income"}, {"person_age", "age"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"loan_to_income", Percentage.Type}, {"amount", Currency.Type}, {"income", Currency.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "status", each if [loan_status] = 1 then "Default" else if [loan_status] = 0 then "Active" else null),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"loan_status"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "interest_rate_n", each [interest_rate] / 100),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"interest_rate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"interest_rate_n", "interest_rate"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"interest_rate", Percentage.Type}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type1",{{"purpose", Text.Proper, type text}, {"residential_status", Text.Proper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Capitalized Each Word", {"residential_status"}, dim_residential_status, {"residential_status"}, "dim_residential_status", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"record_id"}, dim_client, {"client_key"}, "dim_client", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"grade"}, dim_grade, {"grade"}, "dim_grade", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"purpose"}, dim_purpose, {"purpose"}, "dim_purpose", JoinKind.LeftOuter),
				    #"Removed Columns2" = Table.RemoveColumns(#"Merged Queries3",{"credit_history_length", "historic_defaults", "loan_to_income", "grade", "purpose", "employment_length", "residential_status", "income", "age"}),
				    #"Expanded dim_residential_status" = Table.ExpandTableColumn(#"Removed Columns2", "dim_residential_status", {"residential_status_key"}, {"residential_status_key"}),
				    #"Expanded dim_client" = Table.ExpandTableColumn(#"Expanded dim_residential_status", "dim_client", {"client_key"}, {"client_key"}),
				    #"Expanded dim_grade" = Table.ExpandTableColumn(#"Expanded dim_client", "dim_grade", {"grade_key"}, {"grade_key"}),
				    #"Expanded dim_purpose" = Table.ExpandTableColumn(#"Expanded dim_grade", "dim_purpose", {"purpose_key"}, {"purpose_key"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded dim_purpose",{"record_id", "amount", "interest_rate", "status", "residential_status_key", "client_key", "grade_key", "purpose_key"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Reordered Columns1",{"residential_status_key"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Removed Columns3",{"status"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index1" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 0, 1, Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Index1",{{"Index", "status_key"}})
				in
				    #"Renamed Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

