table dim_client
	excludeFromModelRefresh
	lineageTag: 799d1fc9-56f3-445d-bb07-b0ea005863e2

	column client_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f5380162-f290-417e-aa08-dfd9d4039dbf
		summarizeBy: none
		sourceColumn: client_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column age
		dataType: int64
		formatString: 0
		lineageTag: 916f1068-654c-411f-8fdb-f24ffa6ed5f0
		summarizeBy: sum
		sourceColumn: age

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"dim_client","TableItemName":"Age Bins","ObjectType":4},"LinkType":"UsedInGroup"}]

	column income
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 263719c0-487e-4837-9c3e-c060584694d0
		summarizeBy: sum
		sourceColumn: income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"dim_client","TableItemName":"Income Bins","ObjectType":4},"LinkType":"UsedInGroup"}]

	column employment_length
		dataType: double
		lineageTag: 3aabd6e0-1af4-4a7b-b6d1-11153bbf87fc
		summarizeBy: sum
		sourceColumn: employment_length

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"dim_client","TableItemName":"Employment Length Bins","ObjectType":4},"LinkType":"UsedInGroup"}]

	column historic_defaults
		dataType: string
		lineageTag: 984696a4-2e93-4e32-8f4c-e653c8ca0845
		summarizeBy: none
		sourceColumn: historic_defaults

		annotation SummarizationSetBy = Automatic

	column credit_history_length
		dataType: int64
		formatString: 0
		lineageTag: bdb23a65-6c95-41d8-902f-d5a9cc463f69
		summarizeBy: sum
		sourceColumn: credit_history_length

		annotation SummarizationSetBy = Automatic

	column residential_status_key
		dataType: int64
		formatString: 0
		lineageTag: bde5cfe9-5e1c-4c1b-806c-2d8abb96ffb6
		summarizeBy: none
		sourceColumn: residential_status_key

		annotation SummarizationSetBy = Automatic

	column 'Age Bins' =
			IF(
				ISBLANK('dim_client'[age]),
				BLANK(),
				INT('dim_client'[age])
			)
		formatString: 0
		lineageTag: 2a49264d-8a3d-4fff-9873-54350a2b96f3
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "dim_client"
				          }
				        },
				        "Property": "age"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 1.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"dim_client"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"age"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"age"}},"Size":1.0}}}}

		annotation SummarizationSetBy = Automatic

	column 'Income Bins' =
			IF(
				ISBLANK('dim_client'[income]),
				BLANK(),
				INT('dim_client'[income] / 10000) * 10000
			)
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 181c3b4f-07ee-40f0-8ba2-5f8265776505
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "dim_client"
				          }
				        },
				        "Property": "income"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 10000.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"dim_client"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"income"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"income"}},"Size":10000.0}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column 'Employment Length Bins' =
			IF(
				ISBLANK('dim_client'[employment_length]),
				BLANK(),
				IF(
					'dim_client'[employment_length] >= 0,
					ROUNDDOWN('dim_client'[employment_length], 0),
					ROUNDUP('dim_client'[employment_length], 0)
				)
			)
		lineageTag: fbd21ebb-1eb9-4df9-af15-7ba01d4050e9
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "dim_client"
				          }
				        },
				        "Property": "employment_length"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 1.0,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"d","Entity":"dim_client"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"employment_length"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"d"}},"Property":"employment_length"}},"Size":1.0}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_client = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "credit_risk_data", [ReturnSingleDatabase=true]),
				    credit_risk_data_credit_risk_dataset = Source{[Schema="credit_risk_data",Item="credit_risk_dataset"]}[Data],
				    #"Added Index" = Table.AddIndexColumn(credit_risk_data_credit_risk_dataset, "Index", 0, 1, Int64.Type),
				    #"Renamed Columns [index]" = Table.RenameColumns(#"Added Index",{{"Index", "record_id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns [index]",{"record_id", "person_age", "person_income", "person_home_ownership", "person_emp_length", "loan_intent", "loan_grade", "loan_amnt", "loan_int_rate", "loan_status", "loan_percent_income", "cb_person_default_on_file", "cb_person_cred_hist_length"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"loan_intent", "purpose"}, {"loan_amnt", "amount"}, {"loan_int_rate", "interest_rate"}, {"loan_percent_income", "loan_to_income"}, {"cb_person_default_on_file", "historic_defaults"}, {"cb_person_cred_hist_length", "credit_history_length"}, {"loan_grade", "grade"}, {"person_emp_length", "employment_length"}, {"person_home_ownership", "residential_status"}, {"person_income", "income"}, {"person_age", "age"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"loan_to_income", Percentage.Type}, {"amount", Currency.Type}, {"income", Currency.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "status", each if [loan_status] = 1 then "Default" else if [loan_status] = 0 then "Active" else null),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"loan_status"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "interest_rate_n", each [interest_rate] / 100),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"interest_rate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"interest_rate_n", "interest_rate"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"interest_rate", Percentage.Type}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type1",{{"purpose", Text.Proper, type text}, {"residential_status", Text.Proper, type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Capitalized Each Word",{{"record_id", "client_key"}}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Renamed Columns2",{"purpose", "grade", "amount", "loan_to_income", "status", "interest_rate"}),
				    #"Merged Queries" = Table.NestedJoin(#"Removed Columns2", {"residential_status"}, dim_residential_status, {"residential_status"}, "dim_residential_status", JoinKind.LeftOuter),
				    #"Removed Columns3" = Table.RemoveColumns(#"Merged Queries",{"residential_status"}),
				    #"Expanded dim_residential_status" = Table.ExpandTableColumn(#"Removed Columns3", "dim_residential_status", {"residential_status_key"}, {"residential_status_key"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded dim_residential_status","Y","Yes",Replacer.ReplaceText,{"historic_defaults"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","N","No",Replacer.ReplaceText,{"historic_defaults"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

