table fact_records
	lineageTag: 224d8f87-ac17-48ca-ad9b-27f841baa924

	measure 'Default Records' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_records[record_id]),
			    FILTER(dim_status, dim_status[status] = "Default"),
			    FILTER(dim_client, dim_client[age] <= 30)
			)
		formatString: 0
		displayFolder: [Age Below 30]
		lineageTag: f83eb75c-cff4-4701-a10a-ab7b27dcc9d2

	measure 'Total Records' = CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_client, dim_client[age] <= 30))
		formatString: 0
		displayFolder: [Age Below 30]
		lineageTag: 0caec8ef-cac7-47c1-979b-53b1086f328d

	measure 'Default Rate' = fact_records[Default Records] / fact_records[Total Records]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: [Age Below 30]
		lineageTag: 517d3640-abec-4dc0-91ba-5e9c59f64f95

	measure 'Default Loss' = CALCULATE(SUM(fact_records[amount]), FILTER(dim_status, dim_status[status] = "Default"), FILTER(dim_client, dim_client[age] <= 30) )
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: [Age Below 30]
		lineageTag: 6fb271c0-11eb-4cb6-ac8a-d99c00266e87

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Active Amount' = ```
			CALCULATE(SUM(fact_records[amount]), FILTER(dim_status, dim_status[status] = "Active"), FILTER(dim_client, dim_client[age] <= 30)) 
			```
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: [Age Below 30]
		lineageTag: d071adf0-2209-4b7f-8e92-3b5513338bc1

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Active 30+ Amount' = ```
			CALCULATE(SUM(fact_records[amount]), FILTER(dim_status, dim_status[status] = "Active"), FILTER(dim_client, dim_client[age] > 30 && dim_client[age] <= 65)) 
			```
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: [Age 30 - 100]
		lineageTag: 7fded6c8-e62c-4abe-b6b5-3101ff3e8f87

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Default Loss 30+' = CALCULATE(SUM(fact_records[amount]), FILTER(dim_status, dim_status[status] = "Default"), FILTER(dim_client, dim_client[age] > 30 && dim_client[age] <= 100) )
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		displayFolder: [Age 30 - 100]
		lineageTag: eab71881-f5e5-4259-aa10-7aa42bf3d238

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	measure 'Default Records 30+' =
			
			CALCULATE(
			    DISTINCTCOUNT(fact_records[record_id]),
			    FILTER(dim_status, dim_status[status] = "Default"),
			    FILTER(dim_client, dim_client[age] > 30 && dim_client[age] <= 100)
			)
		formatString: 0
		displayFolder: [Age 30 - 100]
		lineageTag: 544d7113-1368-4256-9d93-050db2c6ce1a

	measure 'Default Rate 30+' = fact_records[Default Records 30+] / fact_records[Total Records 30+]
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: [Age 30 - 100]
		lineageTag: c9a78b10-8b28-48fb-bb1c-378db9312ab8

	measure 'Total Records 30+' = CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_client, dim_client[age] > 30 && dim_client[age] <= 100))
		formatString: 0
		displayFolder: [Age 30 - 100]
		lineageTag: 723d609b-c8f1-4dbd-a7c6-8f3852fcf9d4

	measure 'Active Accounts' = CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_status, dim_status[status] = "Active"))
		formatString: 0
		lineageTag: e195105c-e66b-4e8f-b2b8-dcb4e1ff9e67

	measure 'All accounts' = ```
			DISTINCTCOUNT(fact_records[record_id]) 
			```
		formatString: 0
		lineageTag: 96b02329-5882-41da-a02b-40f6e3a9efed

	measure 'Default Accounts' = CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_status, dim_status[status] = "Default"))
		formatString: 0
		lineageTag: d5c67d8b-f620-42c8-af25-ee26523ed2b4

	measure 'Overall Default Rate' = fact_records[Default Accounts] / fact_records[All accounts]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f4352f67-55b5-4405-8191-f26f6fc14db8

	measure 'Active Over 30 Accounts' = ```
			CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_status, dim_status[status] = "Active"), FILTER(dim_client, dim_client[age] > 30 && dim_client[age] <= 65)) 
			```
		formatString: 0
		displayFolder: [Age 30 - 100]
		lineageTag: 90de3c48-dac4-4a63-986c-568312df6e94

	measure 'Active Accounts < 30' = ```
			CALCULATE(DISTINCTCOUNT(fact_records[record_id]), FILTER(dim_status, dim_status[status] = "Active"), FILTER(dim_client, dim_client[age] <= 30)) 
			```
		formatString: 0
		displayFolder: [Age Below 30]
		lineageTag: c9c09d70-4e12-4240-a4b0-403af801a5eb

	measure 'Percent of all active accounts' = ```
			[Active Accounts < 30]/[Active Accounts] 
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: a70c1d74-fc2f-4db4-bacc-b3fb3e3ed9d8

	measure 'risk_level_classification [dynamic]' =
			
			SWITCH(
			    TRUE(),
			    MAX([risk_score]) <= [Risk Threshold Value], "Low",
			    MAX([risk_score]) <= [Risk Threshold Value] + 0.2, "Medium",
			    MAX([risk_score]) > [Risk Threshold Value] + 0.2, "High",
			    BLANK()
			)
		displayFolder: [Classification Dynamic]
		lineageTag: 0045bf2a-cc61-409d-8bdb-88e6c2e4d5c2

	measure 'low_risk_count [dynamic]' =
			
			CALCULATE(
			    COUNTROWS(fact_records),
			    FILTER(fact_records, [risk_score] <= [Risk Threshold Value]),
			    FILTER(dim_status, dim_status[status] = "Active"),
			    FILTER(dim_client, dim_client[age] <= 30)
			)
		formatString: 0
		displayFolder: [Classification Dynamic]
		lineageTag: 8f6ea65a-7e14-46ad-b6d1-6cf872adc97c

	measure 'medium_risk_count [dynamic]' = ```
			
			CALCULATE(
			    COUNTROWS(fact_records),
			    FILTER(fact_records, 
			        [risk_score] > [Risk Threshold Value] &&
			        [risk_score] <= [Risk Threshold Value] + 0.3
			    ),
			    FILTER(dim_status, dim_status[status] = "Active"),
			    FILTER(dim_client, dim_client[age] <= 30)
			)
			```
		formatString: 0
		displayFolder: [Classification Dynamic]
		lineageTag: f63dbcd6-94bd-4830-b38e-e36644a592bb

	measure 'high_risk_count [dynamic]' =
			
			CALCULATE(
			    COUNTROWS(fact_records),
			    FILTER(fact_records, [risk_score] > [Risk Threshold Value] + 0.3),
			    FILTER(dim_status, dim_status[status] = "Active"),
			    FILTER(dim_client, dim_client[age] <= 30)
			)
		formatString: 0
		displayFolder: [Classification Dynamic]
		lineageTag: a367122c-a2b6-430a-a728-784d926a12df

	measure 'High Risk Accounts' = ```
			CALCULATE(
			    DISTINCTCOUNT(fact_records[record_id]), 
			    FILTER(dim_status, dim_status[status] = "Active"), 
			    FILTER(dim_client, dim_client[age] <= 30),
			    FILTER(fact_records, fact_records[risk_level_static] = "High")
			)
			```
		formatString: 0
		displayFolder: [Classification Static]
		lineageTag: e6a87b07-521d-4cf0-b96c-fcc673dea6a1

	measure 'Medium Risk Accounts' = ```
			CALCULATE(
			    DISTINCTCOUNT(fact_records[record_id]), 
			    FILTER(dim_status, dim_status[status] = "Active"), 
			    FILTER(dim_client, dim_client[age] <= 30),
			    FILTER(fact_records, fact_records[risk_level_static] = "Medium")
			)
			```
		formatString: 0
		displayFolder: [Classification Static]
		lineageTag: 18166434-e42a-4ad3-b93e-28caf69269be

	measure 'Low Risk Accounts' = ```
			CALCULATE(
			    DISTINCTCOUNT(fact_records[record_id]), 
			    FILTER(dim_status, dim_status[status] = "Active"), 
			    FILTER(dim_client, dim_client[age] <= 30),
			    FILTER(fact_records, fact_records[risk_level_static] = "Low")
			)
			```
		formatString: 0
		displayFolder: [Classification Static]
		lineageTag: 5333eb7e-b880-46dc-a980-841c13c0af66

	measure 'Static vs Dynamic Classification Change' =
			IF(
			    [High Risk Accounts] <> [high_risk_count [dynamic]]],
			    DIVIDE(
			        [high_risk_count [dynamic]]] - [High Risk Accounts],
			        [High Risk Accounts]
			    ),
			    BLANK()
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: [Classification Comparison]
		lineageTag: 79141b81-3f28-4337-9ceb-be7977a9f4e9

	column record_id
		dataType: int64
		formatString: 0
		lineageTag: 887b98db-8937-4915-bce5-b9e264c68ddb
		summarizeBy: sum
		sourceColumn: record_id

		annotation SummarizationSetBy = Automatic

	column amount
		dataType: decimal
		formatString: "£"#,0.###############;-"£"#,0.###############;"£"#,0.###############
		lineageTag: 3a5da7be-cee7-4ad7-8b36-cbd3a87a5c53
		summarizeBy: sum
		sourceColumn: amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-GB"}

	column interest_rate
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 81d44b95-1edf-4568-8bb8-b79e1e9cd14b
		summarizeBy: sum
		sourceColumn: interest_rate

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"fact_records","TableItemName":"interest_rate (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column client_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8c3f7be1-3361-4d25-af5a-7e063f3ebef6
		summarizeBy: none
		sourceColumn: client_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column grade_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 05c5a17c-43eb-46ac-8587-eb24db921424
		summarizeBy: none
		sourceColumn: grade_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column purpose_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 2005048b-4e18-449a-94dc-69791c276271
		summarizeBy: none
		sourceColumn: purpose_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column status_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3f52d6e0-b1f5-4c9b-8ccd-15f403328ddb
		summarizeBy: none
		sourceColumn: status_key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column loan_to_income
		dataType: double
		lineageTag: f689e3d7-16d4-44bf-9cc9-1ce19e5d558b
		summarizeBy: sum
		sourceColumn: loan_to_income

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"fact_records","TableItemName":"loan_to_income (bins)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column residential_status_key
		dataType: int64
		formatString: 0
		lineageTag: ed1d060f-7079-4493-bbee-05d9fa35677f
		summarizeBy: sum
		sourceColumn: residential_status_key

		annotation SummarizationSetBy = Automatic

	column 'loan_to_income (bins)' =
			IF(
				ISBLANK('fact_records'[loan_to_income]),
				BLANK(),
				IF(
					'fact_records'[loan_to_income] >= 0,
					ROUNDDOWN('fact_records'[loan_to_income] / 0.05, 0) * 0.05,
					ROUNDUP('fact_records'[loan_to_income] / 0.05, 0) * 0.05
				)
			)
		lineageTag: 985a94f7-aa45-44aa-ac15-04fd5fb1aeae
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "fact_records"
				          }
				        },
				        "Property": "loan_to_income"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 0.05,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"fact_records"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"loan_to_income"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"loan_to_income"}},"Size":0.05}}}}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'interest_rate (bins)' =
			IF(
				ISBLANK('fact_records'[interest_rate]),
				BLANK(),
				IF(
					'fact_records'[interest_rate] >= 0,
					ROUNDDOWN('fact_records'[interest_rate] / 0.01, 0) * 0.01,
					ROUNDUP('fact_records'[interest_rate] / 0.01, 0) * 0.01
				)
			)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 4ed1203e-1324-4f21-b459-75bf14f1983b
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "fact_records"
				          }
				        },
				        "Property": "interest_rate"
				      }
				    }
				  ],
				  "binningMetadata": {
				    "binSize": {
				      "value": 0.01,
				      "unit": 0
				    }
				  }
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"f","Entity":"fact_records"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"interest_rate"}}],"BinItem":{"Expression":{"Floor":{"Expression":{"Column":{"Expression":{"SourceRef":{"Source":"f"}},"Property":"interest_rate"}},"Size":0.01}}}}

		annotation SummarizationSetBy = Automatic

	column risk_score
		dataType: double
		displayFolder: [Classification Dynamic]
		lineageTag: 0db5735a-25a1-42aa-b2fe-896b8eb4446b
		summarizeBy: sum
		sourceColumn: risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column risk_level_static =
			
			SWITCH(
			    TRUE(),
			    [risk_score] <= 0.3, "Low",
			    [risk_score] <= 0.6, "Medium",
			    [risk_score] > 0.6, "High",
			    BLANK()
			)
		lineageTag: 48367577-b184-400a-b338-c24621d253df
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition fact_records = m
		mode: import
		source =
				let
				    Source = MySQL.Database("127.0.0.1", "credit_risk_data", [ReturnSingleDatabase=true]),
				    credit_risk_data_credit_risk_dataset = Source{[Schema="credit_risk_data",Item="credit_risk_dataset"]}[Data],
				    #"Added Index" = Table.AddIndexColumn(credit_risk_data_credit_risk_dataset, "Index", 0, 1, Int64.Type),
				    #"Renamed Columns [index]" = Table.RenameColumns(#"Added Index",{{"Index", "record_id"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns [index]",{"record_id", "person_age", "person_income", "person_home_ownership", "person_emp_length", "loan_intent", "loan_grade", "loan_amnt", "loan_int_rate", "loan_status", "loan_percent_income", "cb_person_default_on_file", "cb_person_cred_hist_length"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"loan_intent", "purpose"}, {"loan_amnt", "amount"}, {"loan_int_rate", "interest_rate"}, {"loan_percent_income", "loan_to_income"}, {"cb_person_default_on_file", "historic_defaults"}, {"cb_person_cred_hist_length", "credit_history_length"}, {"loan_grade", "grade"}, {"person_emp_length", "employment_length"}, {"person_home_ownership", "residential_status"}, {"person_income", "income"}, {"person_age", "age"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"loan_to_income", Percentage.Type}, {"amount", Currency.Type}, {"income", Currency.Type}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Changed Type", "status", each if [loan_status] = 1 then "Default" else if [loan_status] = 0 then "Active" else null),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"loan_status"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Columns", "interest_rate_n", each [interest_rate] / 100),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom",{"interest_rate"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"interest_rate_n", "interest_rate"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns1",{{"interest_rate", Percentage.Type}}),
				    #"Capitalized Each Word" = Table.TransformColumns(#"Changed Type1",{{"purpose", Text.Proper, type text}, {"residential_status", Text.Proper, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Capitalized Each Word", {"residential_status"}, dim_residential_status, {"residential_status"}, "dim_residential_status", JoinKind.LeftOuter),
				    #"Merged Queries1" = Table.NestedJoin(#"Merged Queries", {"record_id"}, dim_client, {"client_key"}, "dim_client", JoinKind.LeftOuter),
				    #"Merged Queries2" = Table.NestedJoin(#"Merged Queries1", {"grade"}, dim_grade, {"grade"}, "dim_grade", JoinKind.LeftOuter),
				    #"Merged Queries3" = Table.NestedJoin(#"Merged Queries2", {"purpose"}, dim_purpose, {"purpose"}, "dim_purpose", JoinKind.LeftOuter),
				    #"Expanded dim_residential_status" = Table.ExpandTableColumn(#"Merged Queries3", "dim_residential_status", {"residential_status_key"}, {"residential_status_key"}),
				    #"Expanded dim_client" = Table.ExpandTableColumn(#"Expanded dim_residential_status", "dim_client", {"client_key"}, {"client_key"}),
				    #"Expanded dim_grade" = Table.ExpandTableColumn(#"Expanded dim_client", "dim_grade", {"grade_key"}, {"grade_key"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded dim_grade","Homeimprovement","Home Improvements",Replacer.ReplaceText,{"purpose"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Debtconsolidation","Debt Consolidation",Replacer.ReplaceText,{"purpose"}),
				    #"Merged Queries4" = Table.NestedJoin(#"Replaced Value1", {"purpose"}, dim_purpose, {"purpose"}, "dim_purpose.1", JoinKind.LeftOuter),
				    #"Expanded dim_purpose.1" = Table.ExpandTableColumn(#"Merged Queries4", "dim_purpose.1", {"purpose_key"}, {"purpose_key"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Expanded dim_purpose.1",{"dim_purpose"}),
				    #"Merged Queries5" = Table.NestedJoin(#"Removed Columns2", {"status"}, dim_status, {"status"}, "dim_status", JoinKind.LeftOuter),
				    #"Expanded dim_status" = Table.ExpandTableColumn(#"Merged Queries5", "dim_status", {"status_key"}, {"status_key"}),
				    #"Removed Columns3" = Table.RemoveColumns(#"Expanded dim_status",{"status", "historic_defaults", "credit_history_length", "residential_status", "grade", "purpose", "income", "age", "employment_length"}),
				    #"Merged Queries6" = Table.NestedJoin(#"Removed Columns3", {"record_id"}, #"credit_risk_data credit_risk_dataset", {"record_id"}, "credit_risk_data credit_risk_dataset", JoinKind.LeftOuter),
				    #"Expanded credit_risk_data credit_risk_dataset" = Table.ExpandTableColumn(#"Merged Queries6", "credit_risk_data credit_risk_dataset", {"risk_score"}, {"risk_score"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Expanded credit_risk_data credit_risk_dataset",{{"risk_score", type number}})
				in
				    #"Changed Type2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

